import { defineConfig } from 'oxlint';

export { defineConfig };

export const baseConfig = defineConfig({
  options: {
    typeAware: true,
  },
  plugins: [
    'eslint',
    'typescript',
    'unicorn',
    'react',
    'oxc',
    'import',
    'jsx-a11y',
  ],
  jsPlugins: [
    '@stylistic/eslint-plugin',
  ],
  rules: {
    // eslint
    'accessor-pairs': 'error',
    'array-callback-return': 'error',
    'default-case-last': 'error',
    'eqeqeq': ['error', 'always', { 'null': 'ignore' }],
    'func-name-matching': 'error',
    'grouped-accessor-pairs': ['error', 'getBeforeSet', { enforceForTSTypes: true }],
    'guard-for-in': 'error',
    'max-params': ['error', { max: 4, countThis: 'never' }],
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-case-declarations': 'error',
    'no-constructor-return': 'error',
    'no-div-regex': 'error',
    'no-duplicate-imports': 'error',
    'no-else-return': ['error', { allowElseIf: false }],
    'no-empty': 'error',
    'no-empty-function': ['error', { allow: ['arrowFunctions'] }],
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-fallthrough': ['error', { allowEmptyCase: true }],
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    'no-multi-assign': 'error',
    'no-multi-str': 'error',
    'no-negated-condition': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-object-constructor': 'error',
    'no-param-reassign': 'error',
    'no-promise-executor-return': 'error',
    'no-proto': 'error',
    'no-prototype-builtins': 'error',
    'no-regex-spaces': 'error',
    'no-return-assign': ['error', 'always'],
    'no-script-url': 'error',
    'no-self-compare': 'error',
    'no-sequences': ['error', { allowInParentheses: false }],
    'no-shadow': 'error',
    'no-template-curly-in-string': 'error',
    'no-unneeded-ternary': 'error',
    'no-unreachable-loop': 'error',
    'no-useless-assignment': 'error',
    'no-useless-call': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'operator-assignment': 'error',
    'prefer-const': ['error', { destructuring: 'all' }],
    'prefer-numeric-literals': 'error',
    'prefer-object-has-own': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'radix': 'error',
    'symbol-description': 'error',

    // typescript
    'typescript/adjacent-overload-signatures': 'error',
    'typescript/consistent-generic-constructors': ['error', 'constructor'],
    'typescript/consistent-indexed-object-style': ['error', 'record'],
    'typescript/consistent-type-exports': 'error',
    'typescript/dot-notation': 'error',
    'typescript/explicit-module-boundary-types': 'error',
    'typescript/method-signature-style': ['error', 'property'],
    'typescript/no-confusing-non-null-assertion': 'error',
    'typescript/no-dynamic-delete': 'error',
    'typescript/no-empty-interface': ['error', { allowSingleExtends: true }],
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extraneous-class': 'error',
    'typescript/no-import-type-side-effects': 'error',
    'typescript/no-inferrable-types': 'error',
    'typescript/no-meaningless-void-operator': 'error',
    'typescript/no-misused-promises': 'error',
    'typescript/no-mixed-enums': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-nullish-coalescing': 'error',
    'typescript/no-non-null-assertion': 'error',
    'typescript/no-this-alias': ['error', { allowedNames: ['self'] }],
    'typescript/no-unnecessary-template-expression': 'error',
    'typescript/no-unnecessary-type-assertion': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unnecessary-type-conversion': 'error',
    'typescript/no-unnecessary-type-parameters': 'error',
    'typescript/no-unsafe-argument': 'error',
    'typescript/no-unsafe-assignment': 'error',
    'typescript/no-unsafe-call': 'error',
    'typescript/no-unsafe-enum-comparison': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-unsafe-member-access': 'error',
    'typescript/no-unsafe-return': 'error',
    'typescript/only-throw-error': 'error',
    'typescript/prefer-find': 'error',
    'typescript/prefer-promise-reject-errors': 'error',
    'typescript/prefer-readonly': 'error',
    'typescript/prefer-reduce-type-parameter': 'error',
    'typescript/prefer-regexp-exec': 'error',
    'typescript/prefer-return-this-type': 'error',
    'typescript/prefer-string-starts-ends-with': 'error',
    'typescript/prefer-ts-expect-error': 'error',
    'typescript/related-getter-setter-pairs': 'error',
    'typescript/require-await': 'error',
    'typescript/restrict-plus-operands': 'error',

    // unicorn
    // Only default rules
    'unicorn/no-useless-spread': 'error',

    // react
    'react/button-has-type': ['error', { button: true, submit: true, reset: false }],
    'react/capitalized-calls': 'error',
    'react/checked-requires-onchange-or-readonly': 'error',
    'react/display-name': 'error',
    'react/error-boundaries': 'error',
    'react/exhaustive-deps': 'error',
    'react/exhaustive-effect-dependencies': 'error',
    'react/forward-ref-uses-ref': 'error',
    'react/globals': 'error',
    'react/hook-use-state': ['error', { allowDestructuredState: true }],
    'react/hooks': 'error',
    'react/iframe-missing-sandbox': 'error',
    'react/immutability': 'error',
    'react/incompatible-library': 'error',
    'react/jsx-fragments': 'error',
    'react/jsx-key': 'error',
    'react/jsx-no-comment-textnodes': 'error',
    'react/jsx-no-constructed-context-values': 'error',
    'react/jsx-no-duplicate-props': 'error',
    'react/jsx-no-useless-fragment': 'error',
    'react/jsx-pascal-case': 'error',
    'react/jsx-props-no-spread-multi': 'error',
    'react/memo-dependencies': 'error',
    'react/no-array-index-key': 'error',
    'react/no-children-prop': 'error',
    'react/no-clone-element': 'error',
    'react/no-deriving-state-in-effects': 'error',
    'react/no-react-children': 'error',
    'react/no-this-in-sfc': 'error',
    'react/no-unescaped-entities': 'error',
    'react/no-unknown-property': ['error', { requireDataLowercase: true }],
    'react/no-unstable-nested-components': 'error',
    'react/only-export-components': 'error',
    'react/prefer-function-component': 'error',
    'react/preserve-manual-memoization': 'error',
    'react/purity': 'error',
    'react/refs': 'error',
    'react/rule-suppression': 'off',
    'react/rules-of-hooks': 'error',
    'react/self-closing-comp': 'error',
    'react/set-state-in-effect': 'error',
    'react/set-state-in-render': 'error',
    'react/static-components': 'error',
    'react/style-prop-object': 'error',
    'react/syntax': 'error',
    'react/use-memo': 'error',
    'react/void-dom-elements-no-children': 'error',
    'react/void-use-memo': 'error',

    // oxc
    // Only default rules

    // import
    'import/default': 'error',
    'import/export': 'error',
    'import/first': 'error',
    'import/named': 'error',
    'import/namespace': 'error',
    'import/newline-after-import': 'error',
    'import/no-absolute-path': 'error',
    'import/no-cycle': 'error',
    'import/no-duplicates': 'error',
    'import/no-empty-named-blocks': 'error',
    'import/no-mutable-exports': 'error',
    'import/no-named-as-default': 'error',
    'import/no-named-as-default-member': 'error',
    'import/no-self-import': 'error',

    // jsx-a11y
    'jsx-a11y/alt-text': 'error',
    'jsx-a11y/anchor-has-content': 'error',
    'jsx-a11y/anchor-is-valid': 'error',
    'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
    'jsx-a11y/aria-props': 'error',
    'jsx-a11y/aria-proptypes': 'error',
    'jsx-a11y/aria-role': 'error',
    'jsx-a11y/aria-unsupported-elements': 'error',
    'jsx-a11y/autocomplete-valid': 'error',
    'jsx-a11y/click-events-have-key-events': 'error',
    'jsx-a11y/control-has-associated-label': 'error',
    'jsx-a11y/heading-has-content': 'error',
    'jsx-a11y/html-has-lang': 'error',
    'jsx-a11y/iframe-has-title': 'error',
    'jsx-a11y/interactive-supports-focus': 'error',
    'jsx-a11y/label-has-associated-control': 'error',
    'jsx-a11y/media-has-caption': 'error',
    'jsx-a11y/mouse-events-have-key-events': 'error',
    'jsx-a11y/no-access-key': 'error',
    'jsx-a11y/no-aria-hidden-on-focusable': 'error',
    'jsx-a11y/no-autofocus': 'error',
    'jsx-a11y/no-distracting-elements': 'error',
    'jsx-a11y/no-interactive-element-to-noninteractive-role': 'error',
    'jsx-a11y/no-noninteractive-element-interactions': 'error',
    'jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
    'jsx-a11y/no-noninteractive-tabindex': 'error',
    'jsx-a11y/no-redundant-roles': 'error',
    'jsx-a11y/no-static-element-interactions': 'error',
    'jsx-a11y/prefer-tag-over-role': 'off',
    'jsx-a11y/role-has-required-aria-props': 'error',
    'jsx-a11y/role-supports-aria-props': 'error',
    'jsx-a11y/scope': 'error',
    'jsx-a11y/tabindex-no-positive': 'error',

    // @stylistic/eslint-plugin
    '@stylistic/no-confusing-arrow': 2,
    '@stylistic/no-floating-decimal': 2,
    '@stylistic/quote-props': ['error', 'as-needed'],
    '@stylistic/array-bracket-spacing': 2,
    '@stylistic/arrow-parens': ['error', 'as-needed'],
    '@stylistic/arrow-spacing': 2,
    '@stylistic/block-spacing': 2,
    '@stylistic/brace-style': 2,
    '@stylistic/comma-dangle': ['error', 'always-multiline'],
    '@stylistic/comma-spacing': 2,
    '@stylistic/comma-style': 2,
    '@stylistic/computed-property-spacing': 2,
    '@stylistic/dot-location': ['error', 'property'],
    '@stylistic/eol-last': 2,
    '@stylistic/function-call-spacing': 2,
    '@stylistic/indent': ['error', 2, { SwitchCase: 1 }],
    '@stylistic/jsx-quotes': ['error', 'prefer-single'],
    '@stylistic/key-spacing': 2,
    '@stylistic/keyword-spacing': 2,
    '@stylistic/lines-between-class-members': [
      'error',
      'always',
      { 'exceptAfterSingleLine': true },
    ],
    '@stylistic/max-len': ['error', { code: 100 }],
    '@stylistic/max-statements-per-line': ['error', { max: 1 }],
    '@stylistic/multiline-ternary': ['error', 'always-multiline'],
    '@stylistic/new-parens': 2,
    '@stylistic/no-extra-parens': ['error', 'all', { ignoreJSX: 'multi-line' }],
    '@stylistic/no-multi-spaces': 2,
    '@stylistic/no-multiple-empty-lines': 2,
    '@stylistic/no-tabs': 2,
    '@stylistic/no-trailing-spaces': 2,
    '@stylistic/no-whitespace-before-property': 2,
    '@stylistic/nonblock-statement-body-position': ['error', 'beside'],
    '@stylistic/object-curly-newline': ['error', { 'consistent': true }],
    '@stylistic/object-curly-spacing': ['error', 'always'],
    '@stylistic/operator-linebreak': ['error', 'after', {
      overrides: {
        '?': 'before',
        ':': 'before',
        '|': 'ignore',
      },
    }],
    '@stylistic/padded-blocks': ['error', 'never'],
    '@stylistic/quotes': ['error', 'single'],
    '@stylistic/rest-spread-spacing': ['error', 'never'],
    '@stylistic/semi': 2,
    '@stylistic/semi-spacing': 2,
    '@stylistic/semi-style': 2,
    '@stylistic/space-before-blocks': 2,
    '@stylistic/space-before-function-paren': ['error', {
      anonymous: 'never',
      named: 'never',
      asyncArrow: 'never',
      catch: 'always',
    }],
    '@stylistic/space-in-parens': 2,
    '@stylistic/space-infix-ops': 2,
    '@stylistic/space-unary-ops': 2,
    '@stylistic/switch-colon-spacing': 2,
    '@stylistic/template-curly-spacing': 2,
    '@stylistic/template-tag-spacing': 2,
    '@stylistic/wrap-iife': 2,
    '@stylistic/wrap-regex': 2,
    '@stylistic/yield-star-spacing': 2,
  },
});
